#! /bin/sh

donttouch_check(){
	TEST=$(echo "$1" | grep "Project")
	if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "conf")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "local")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "share")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "keep")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep ".*rc")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "$HOME/Books")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "$HOME/Music")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "$HOME/Videos")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "WORKING_")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "README")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "INSTALL")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "HACKING")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "SCRIPTING")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "COPYING")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "mozilla")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "package")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "icedove")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "client")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "static")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "markdown.js")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "models")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "server")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "video")
		if [ -z $TEST ]; then
		TEST=$(echo "$1" | grep "public")
		if [ -z $TEST ]; then
			mv "$1" "$2"
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
		fi
	fi
}

find_and_move(){
	PATTERN="$1"
	DIRECTORY="$2"
	LIST=$(find "$HOME" -name "$PATTERN" 2> /dev/null)
	for f in $LIST; do
		if [ -f $f ]; then
		if [ -d "$DIRECTORY" ]; then
			donttouch_check "$f" "$DIRECTORY"
		else
			mkdir -p "$DIRECTORY"
			donttouch_check "$f" "$DIRECTORY"
		fi
		fi
	done
}
DOCS="*.txt 
*.html 
*.abw 
*.doc 
*.odt 
*.docx "
for t in $DOCS; do
	find_and_move "$t" "$HOME/Documents" 2> /dev/null
done
SHEETS="*.gnumeric 
*.csv 
*.xls
*.ods  
*.xlsx "
for t in $SHEETS; do
	find_and_move "$t" "$HOME/Documents/Spreadsheets" 2> /dev/null
done
DIAGRAM="*.dia 
*.svg "
for t in $DIAGRAM; do
	find_and_move "$t" "$HOME/Documents/Diagrams" 2> /dev/null
done
TEXT="*.pdf 
*.ps 
*.epub "
for t in $TEXT; do
	find_and_move "$t" "$HOME/Books" 2> /dev/null
done
AUDIO="*.ogg 
*.flac 
*.mp3 
*.ogg "
for t in $AUDIO; do
	find_and_move "$t" "$HOME/Music" 2> /dev/null
done
VIDEO="*.mkv 
*.mp4 
*.mpeg 
*.ogv "
for t in $VIDEO; do
	find_and_move "$t" "$HOME/Videos" 2> /dev/null
done
SAMPLES="*.js
*.json
*.css
*.php
*.sh
*.bin "
for t in $SAMPLES; do
	find_and_move "$t" "$HOME/Documents/Samples" 2> /dev/null
done
